### ISSUE TITLE
Sample app not creating projection

### ISSUE THREAD

**Issue by cfjedimaster** [serialized-io/samples-js#1]
I signed up for an account and got my keys. Cloned the repo, set the env variables, and started the app:

```
ray@Mandalore:~/.../serialized/samples-js/todo-application-js$ npm run start

> todos@1.0.0 start
> node -r ./src/app.js

Starting todos-application...
Updating projection: list-stats
Welcome to Node.js v17.2.0.
Type ".help" for more information.
> Updating projection: lists
Application todos-application is up and running.
API is available at: https://localhost:8888
```

When I hit the site, I get: 

```json
{
  "error": {
    "isSerializedError": true,
    "statusCode": 404,
    "isSerializedApiError": true,
    "projectionName": "lists",
    "name": "ProjectionNotFound"
  }
}
```

Which is odd because in the terminal, it said lists was made.

**Comment by jeham** [comment]
Hi!
The initial projection setup can take up to 30 seconds as it's an async process on the server side.
If you try again now I think it will work as expected.
If not, please login to the web console (https://app.serialized.io/) and verify that the projections is listed in the "Projections" section.
We should display a better message until the projections are available - thanks for making us aware of this!

**Comment by cfjedimaster** [comment]
Can confirm - thank you.
